# Generated by Django 3.2.12 on 2024-05-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('numTel', models.IntegerField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('sujet', models.TextField(max_length=500)),
                ('adresseGoogle', models.TextField()),
                ('photo', models.CharField(max_length=50)),
            ],
        ),
    ]
