# Generated by Django 3.2.12 on 2024-05-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commune', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='numTel',
            field=models.IntegerField(),
        ),
    ]
