# Generated by Django 3.2.12 on 2024-05-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commune', '0002_alter_reclamation_numtel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='adresseGoogle',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='numTel',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='sujet',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
